name: openzeppelin
base: core18
version: git
summary: OpenZeppelin commmand-line interface
description: |
  OpenZeppelin SDK is a platform to develop, deploy and operate smart
  contract projects on Ethereum and every other EVM and eWASM-powered
  blockchain.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  openzeppelin:
    command: usr/local/bin/node $SNAP/lib/bin/oz-cli.js
    environment: 
      PATH: $SNAP/usr/local/bin/:$PATH 
      NODE_PATH: $SNAP/node_modules:$NODE_PATH
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
    plugs: [home, network]

parts:
  openzeppelin:
    source: .
    # XXX Cannot use the nodejs plugin because of https://pad.lv/1694642
    # --elopio - 2019-08-05
    plugin: dump
    build-packages: [make, g++, python]
    stage-packages:
      # Needed for $ openzeppelin unpack tutorial
      - git-core
      - build-essential
      - make
      - g++
      - python
    override-build: |
      export PATH=$SNAPCRAFT_STAGE/usr/local/bin/:$PATH
      cd packages/cli
      # FIXME these packages should be in the package.json
      # --elopio - 2019-08-05
      npm install web3-eth web3-eth-contract
      # XXX workaround for https://github.com/OpenZeppelin/openzeppelin-sdk/issues/929
      # --elopio - 2019-08-06
      rm -rf node_modules/websocket/.git
      rm -rf node_modules/web3/node_modules/websocket/.git
      # XXX These files trigger a manual snap review from lint-snap-v2_iffy_files
      # --elopio - 2019-08-10
      rm -rf node_modules/web3/node_modules/tar/lib/.mkdir.js.swp
      rm -rf node_modules/web3-eth-accounts/node_modules/semver/bin/.semver.js.swp
      npm install --unsafe-perm
      cp package.json $SNAPCRAFT_PART_INSTALL
      cp -r lib $SNAPCRAFT_PART_INSTALL
      cp -r node_modules $SNAPCRAFT_PART_INSTALL
    after: [node]
  node:
    plugin: autotools
    source: https://nodejs.org/dist/v10.16.1/node-v10.16.1.tar.gz
    build-packages: [g++, make, python]
